site_name: CommunityToolkit - 从入门到精通
site_url: http://blog.yunwuyue.xyz/CommunityToolkit.Mvvm_ZeroToHero/

repo_name: CommunityToolkit.Mvvm_ZeroToHero
repo_url: https://github.com/BYJRK/CommunityToolkit.Mvvm_ZeroToHero

theme:
  name: material
  language: zh
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - search.suggest
    - navigation.footer
    - content.tooltips
    - content.tabs.link
    - content.code.annotate
  icon:
    annotation: material/arrow-right-circle
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - tags:
      tags_file: tags.md
  - search

nav:
  - 首页: index.md
  - MVVM Basics (WIP):
    # - INotifyPropertyChanged
    # - INotifyCollectionChanged
    # - INotifyDataErrorInfo
    # - ICommand
    - Model vs. ViewModel: MVVM Basics/ModelVsViewModel.md
  - ComponentModel:
    - ObservableObect:
      - ObservableObect: ComponentModel/ObservableObject/index.md
      - OnPropertyChanged: ComponentModel/ObservableObject/OnPropertyChanged.md
      - SetProperty: ComponentModel/ObservableObject/SetProperty.md
    - ObservableRecipient (WIP):
      - ObservableRecipient: ComponentModel/ObservableRecipient.md
    - ObservableValidator (WIP):
      - ObservableValidator: ComponentModel/ObservableValidator.md
  - RelayCommand (WIP):
    - RelayCommand: RelayCommand/RelayCommand.md
    - AsyncRelayCommand: RelayCommand/AsyncRelayCommand.md
  - Messengers (WIP):
    - IMessenger: Messengers/IMessenger.md
    - WeakReferenceMessenger: Messengers/WeakReferenceMessenger.md
    - StrongReferenceMessenger: Messengers/StrongReferenceMessenger.md
  - DependencyInjection (WIP):
    - IHost: DependencyInjection/IHost.md
    - IServiceProvider: DependencyInjection/IServiceProvider.md