site_name: CommunityToolkit - 从入门到精通
site_url: http://blog.yunwuyue.xyz/CommunityToolkit.Mvvm_ZeroToHero/

repo_name: CommunityToolkit.Mvvm_ZeroToHero
repo_url: https://github.com/BYJRK/CommunityToolkit.Mvvm_ZeroToHero

theme:
  name: material
  language: zh
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - search.suggest
    - navigation.footer
    - content.tooltips
    - content.tabs.link
    - content.code.annotate
  icon:
    annotation: material/arrow-right-circle
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - tags:
      tags_file: tags.md
  - search

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

nav:
  - 首页: index.md
  - 快速开始:
    - Quick Start/index.md
  - MVVM 基础 (WIP):
    # - INotifyPropertyChanged
    # - INotifyCollectionChanged
    # - INotifyDataErrorInfo
    # - ICommand
    - MVVM: MVVM Basics/index.md
    - ViewModel: MVVM Basics/ViewModel.md
    - Model vs. ViewModel: MVVM Basics/Model vs. ViewModel.md
  - 组件模型（ComponentModel）:
    - ObservableObect:
      - ComponentModel/ObservableObject/index.md
      - OnPropertyChanged: ComponentModel/ObservableObject/OnPropertyChanged.md
      - SetProperty: ComponentModel/ObservableObject/SetProperty.md
    - ObservableRecipient (WIP):
      - ObservableRecipient: ComponentModel/ObservableRecipient.md
    - ObservableValidator (WIP):
      - ObservableValidator: ComponentModel/ObservableValidator.md
  - 中继指令（RelayCommand） (WIP):
    - RelayCommand: RelayCommand/RelayCommand.md
    - AsyncRelayCommand: RelayCommand/AsyncRelayCommand.md
  - 源生成器（Source Generator） (WIP):
    - Source Generator: Source Generator/index.md
  - 消息中继（Messengers）:
    - Messengers/index.md
    - IMessenger: Messengers/IMessenger.md
    - WeakReferenceMessenger: Messengers/WeakReferenceMessenger.md
    - Messages: Messengers/Messages.md
    - Token: Messengers/Token.md
  - 依赖注入（Dependency Injection） (WIP):
    - Dependency Injection: DependencyInjection/index.md